package com.yqritc.scalablevideoview;

public enum ScalableType {
    LEFT_TOP,
    LEFT_CENTER,
    LEFT_BOTTOM,
    CENTER_TOP,
    CENTER,
    CENTER_BOTTOM,
    RIGHT_TOP,
    RIGHT_CENTER,
    RIGHT_BOTTOM,
    LEFT_TOP_CROP,
    LEFT_CENTER_CROP,
    LEFT_BOTTOM_CROP,
    CENTER_TOP_CROP,
    CENTER_CROP,
    CENTER_BOTTOM_CROP,
    RIGHT_TOP_CROP,
    RIGHT_CENTER_CROP,
    RIGHT_BOTTOM_CROP,
    LEFT_TOP_INSIDE,
    LEFT_CENTER_INSIDE,
    LEFT_BOTTOM_INSIDE,
    CENTER_TOP_INSIDE,
    CENTER_INSIDE,
    CENTER_BOTTOM_INSIDE,
    RIGHT_TOP_INSIDE,
    RIGHT_CENTER_INSIDE,
    RIGHT_BOTTOM_INSIDE,
    FIT_CENTER
}


